[build-system]
requires = [
    "setuptools>=46.4.0",
    "setuptools_scm>=6.2",
    "setuptools_scm_git_archive",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "effmass/_version.py"